Added Sekiro FPS region fix and new aspect ratio feature
leaty/tuxtrain pull request #5
Opened 2023-01-24 12:08 UTC by SvdB-nonp

The FPS memory location was off for me, so I ran it without and used the suggested memory location by the trainer in a subsequent test. For me the regions as they are in the file now work splendidly, but I am not sure if they need to be wider in case it is different on other systems.

As my monitor is 3440x1440 with 165 hz refresh, that is the settings I tested with. FPS changes work with windowed and fullscreen, while the aspect ratio change is for Fullscreen only. For the latter I made a note in the sekiro.toml.

Changing resolution and window modes do not affect the fixes as far as I could tell. Will play the game again to test it more thoroughly and see how stable it is (nice excuse to replay the game).

2023-01-24 22:59 UTC, leaty commented
Nice. I had a little difficulty testing the ultrawide as always (I don't have one). But I got it working with gamescope trickery, so I can confirm the pattern and region works.

However the new region for FPS does not work for me. Could you restore the old region, add yours and lastly comment both of them out? Just in case it differs for someone else as well, so they can just pick and choose or set their own after running it once without.

> Will play the game again to test it more thoroughly and see how stable it is (nice excuse to replay the game).

That's definitely a pretty good excuse :+1:

2023-01-24 22:59 UTC, leaty requested changes

2023-01-24 22:59 UTC, leaty commented on trainers/sekiro.toml
> +region = [5387236685, 5387236695]
Leave both regions there and comment them out.

2023-01-25 08:18 UTC, SvdB-nonp commented
Unfortunate that the region is not always the same. I have kept both regions and commented them as suggested.

2023-01-25 12:55 UTC, leaty approved these changes

2023-01-25 12:57 UTC, merged

2023-01-25 13:06 UTC, leaty commented
> Unfortunate that the region is not always the same. I have kept both regions and commented them as suggested.

Probably different versions/proton/wine *could* cause it but it seems pretty rare so far. I should probably add a message when a pattern isn't found while having the region set, to make it more clear. There is also a way to get the actual game regions making the search a lot smaller and faster (essentially it would skip all the wine/proton/dxvk pages), having that as an option could be useful as most of the normal stuff you'd want to change is within the game itself.